yolo_model:

  config_file:
    name: yolov3-subt-cave.cfg
  weight_file:
    name: 23082020-yolov3-subt-cave.weights
  threshold:
    value: 0.1
  detection_classes:
    names:
      - phone
      - helmet
      - rope
      - backpack
      - survivor
