yolo_model:

  config_file:
    name: yolov3-tiny-subt-cave.cfg
  weight_file:
    name: 20200929-yolov3-tiny-subt-cave.weights
  threshold:
    value: 0.25
  detection_classes:
    names:
      - phone
      - helmet
      - rope
      - backpack
      - survivor
