max_planning_retries: 2
recovery_behavior_enabled: false
controller_patience: 5
oscillation_timeout: 10

local_costmap:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 6.0
    publish_frequency: 2.0
    static_map: false
    rolling_window: true
    width: 20
    height: 20
    resolution: 0.05
    footprint: [[0.25, 0.25], [0.25, -0.25], [-0.25, -0.25], [-0.25, 0.25]]
    transform_tolerance: 5
    update_frequency: 5
    publish_frequency: 5
    plugins:
        - {name: obstacles_laser,     type: "costmap_2d::ObstacleLayer"}
        - {name: obstacles_realsense,     type: "costmap_2d::ObstacleLayer"}
        - {name: inflation,        type: "costmap_2d::InflationLayer"}
    obstacles_laser:
        observation_sources: laser
        laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, obstacle_range: 20,
            raytrace_range: 20, inf_is_valid: true}
    obstacles_realsense:
        observation_sources: realsense
        realsense: {data_type: PointCloud2, clearing: true, marking: true, topic: /camera/depth_registered/points, obstacle_range: 8.0,
            raytrace_range: 8.0, inf_is_valid: false}
    explore_boundary:
        resize_to_boundary: false
        frontier_travel_point: "middle"
        explore_clear_space: false
    inflation:
        inflation_radius: 0.15

global_costmap:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    static_map: false
    rolling_window: true
    width: 20
    height: 20
    resolution: 0.05
    footprint: [[0.25, 0.25], [0.25, -0.25], [-0.25, -0.25], [-0.25, 0.25]]
    transform_tolerance: 5
    update_frequency: 5
    publish_frequency: 5
    plugins:
        - {name: obstacles_laser,     type: "costmap_2d::ObstacleLayer"}
        - {name: inflation,        type: "costmap_2d::InflationLayer"}
    obstacles_laser:
        observation_sources: laser
        laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true}
    explore_boundary:
        resize_to_boundary: false
        frontier_travel_point: "middle"
        explore_clear_space: false
    inflation:
        inflation_radius: 0.15
      

DWAPlannerROS:
     max_vel_x: 0.4
     min_vel_x: -0.1
     max_vel_theta: 0.3
     min_in_place_vel_theta: 0.1
     min_vel_y: 0
     max_vel_y: 0
 #    
     acc_lim_theta: 3.2
     acc_lim_x: 2.5
     acc_lim_y: 2.5
 #
     xy_goal_tolerance: 0.5
     yaw_goal_tolerance: 0.10
     holonomic_robot: false
     occ_dist_scale: 10
     forward_point_distance: 0
     #pdist_scale: 0.1
     #gdist_scale: 0.5
